import "./Topup.css"
import { FaWallet } from "react-icons/fa6";
import { BsCopy } from "react-icons/bs";
const Topup = () => {
    return ( 
        <div className="topup">
            <div className="topup-top">
                <p className="available"><span><FaWallet/></span>Available  balance:</p>
                <p className="available-amount">NGN 13552.64</p>
            </div>
            <div className="topup-card">
                <p>Account Number</p>
                <h4>9888837274322</h4>
                <div className="card-bottom">
                    <p>Credio</p>
                    <BsCopy/>
                </div>
            </div>
            <div className="topup-top">
                <p className="available"><span><FaWallet/></span>Wallet Guide</p>
                <p className="wallet-text">
                    Minimum amount to recharge is N3000.
                    You can use any of our autogenerated virtual account numbers to top up your wallet and any money transferred to these account numbers would be credited to your wallet automatically.
                    If you experience any issue making payment to your wallet, please reach out to support@termii.com or contact any of your account reps via our support channels.
                    We have also included VAT of 7.5% as part of your charges. This means that if you pay 2000 naira, we will credit your wallet with 1850 naira.
                </p>
            </div>
        </div>
     );
}
 
export default Topup;